language: node_js
node_js:
    - 12
cache:
  directories:
    - "node_modules"

branches:
  only:
    - docs

branch: docs

install:
    - npm install
script:
    - npm run build
deploy:
  provider: pages
  local_dir: docs/.vuepress/dist
  skip_cleanup: true
  repo: nusrobomaster/nusrobomaster.github.io
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

